[pytest]
markers =
    smoke: marker for smoke tests
    regression: marker for regression tests
    win10
    login_guest: marker for guest login
    authorized_user: marker for authorized user
    need_review: marker for tests needing review